# Hugo configuration for cads-tech.dev
baseURL = 'https://cads-tech.dev/'
languageCode = 'en-us'
title = 'CaDs'
theme = 'hugo-bearblog'

# Author info
author = 'CaDs'
copyright = 'Copyright Â© 2026, CaDs.'

# Generate robots.txt for SEO
enableRobotsTXT = true

# Bearblog-style URLs
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"

[params]
  description = "A simple tech blog by CaDs"
  dateFormat = "2006-01-02"
  hideMadeWithLine = true

[[menus.main]]
  name = "About"
  url = "/"
  weight = 1

[[menus.main]]
  name = "Thoughts"
  url = "/blog/"
  weight = 2

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = false
    codeFences = true
